[game]
name = "Kingdom Hearts: Chain of Memories"
short_name = "KHCOM"
default_region = "USA"

[rom]
path = "roms/Kingdom Hearts - Chain of Memories (U)(Venom).gba"
sha1 = "10729bd884f8fdca7a310b6d606c52e46657aa48"

[bios]
path = "bios/gba_bios.bin"
sha1 = "300c20df6731a33952ded8c436f7f186d25d3492"
hle = false

[save]
type = "eeprom"
size = 8192

[video]
view_width = 284
max_resize_view_width = 576
resize_view = true

[audio]
shadow = true

[[extra_func]]
addr = 0x02038738
mode = "thumb"

[[extra_func]]
addr = 0x0203875A
mode = "thumb"

[[extra_func]]
addr = 0x03000000
mode = "thumb"

[[extra_func]]
addr = 0x03000060
mode = "thumb"

[[extra_func]]
addr = 0x0300006E
mode = "thumb"

[[extra_func]]
addr = 0x0300007A
mode = "thumb"

[[extra_func]]
addr = 0x03000098
mode = "thumb"

[[extra_func]]
addr = 0x030000AC
mode = "thumb"

[[extra_func]]
addr = 0x030000B8
mode = "thumb"

[[extra_func]]
addr = 0x03000380
mode = "thumb"

[[extra_func]]
addr = 0x0300038A
mode = "thumb"

[[extra_func]]
addr = 0x03006C80
mode = "arm"

[[extra_func]]
addr = 0x03006D50
mode = "arm"

[[extra_func]]
addr = 0x03006D8C
mode = "arm"

