#!/usr/bin/env python3
"""Extract function symbols from the ROM's debug registration tables.

The game registers tasks and modes in descriptor tables (there are several,
e.g. per-world boss task tables), each entry carrying a pointer to a debug
name string followed by function pointers:

  task entry: {name*, fn0, fn1, fn2, fn3, work_size} (24 bytes)
  mode entry: {name*, fn0, fn1, fn2, ram*}           (20 bytes)

Rather than hardcoding table addresses, scan the whole ROM for aligned words
that point at a task_*/mode_* string and validate the words that follow.
Callback semantics are unconfirmed, so functions are named <name>_<index>.
Emits a luvdis config: "thumb_func <addr> <name>" per function.
"""

import argparse
import re
import struct
import sys

ROM_BASE = 0x08000000
CODE_END = ROM_BASE + 0x122000


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("rom")
    parser.add_argument("-o", "--output", default="/dev/stdout")
    args = parser.parse_args()

    data = open(args.rom, "rb").read()

    names = {}
    for m in re.finditer(rb"(?<=\x00)((task|mode)_[A-Za-z0-9_]+)\x00", data):
        nfuncs = 4 if m.group(2) == b"task" else 3
        names[ROM_BASE + m.start(1)] = (m.group(1).decode(), nfuncs)

    def valid_fn(w):
        return w == 0 or (w & 1 and ROM_BASE < w < CODE_END)

    syms = {}
    words = struct.unpack(f"<{len(data)//4}I", data)
    for i, w in enumerate(words):
        if w not in names:
            continue
        name, nfuncs = names[w]
        fns = words[i + 1 : i + 1 + nfuncs]
        if len(fns) == nfuncs and all(map(valid_fn, fns)) and any(fns):
            for k, fn in enumerate(fns):
                if fn:
                    syms.setdefault(fn & ~1, f"{name}_{k}")

    with open(args.output, "w") as f:
        f.write("# generated by tools/gen_symbols.py -- do not edit\n")
        for addr in sorted(syms):
            f.write(f"thumb_func 0x{addr:08X} {syms[addr]}\n")
    print(f"{len(syms)} named functions", file=sys.stderr)


if __name__ == "__main__":
    main()
